version: "3.8"

# extension field for YAML anchor definition
x-env: &comm_env
  environment:
    - GRPC_SECURE="yes"

services:
  #
  # gateway
  #
  gateway:
    build:
      context: ./
      dockerfile: ./cmd/gateway/Dockerfile
    image: ${DOCKER_ID}/srv-gateway:latest
    restart: always
    <<: *comm_env
    volumes:
      - ${PWD}/gen/srv-proto-gateway-go/gateway.swagger.json:/app/gen/srv-proto-gateway-go/gateway.swagger.json
    networks:
      - net
    ports:
      - 8000:8000
  #
  # proxy
  #
  proxy:
    build:
      context: ./
      dockerfile: ./cmd/proxy/Dockerfile
    image: ${DOCKER_ID}/srv-proxy:latest
    restart: always
    <<: *comm_env
    networks:
      - net
  #
  # user
  #
  user:
    build:
      context: ./
      dockerfile: ./cmd/user/Dockerfile
    image: ${DOCKER_ID}/srv-user:latest
    restart: always
    <<: *comm_env
    networks:
      - net
  #
  # company
  #
  company:
    build:
      context: ./
      dockerfile: ./cmd/company/Dockerfile
    image: ${DOCKER_ID}/srv-company:latest
    restart: always
    <<: *comm_env
    networks:
      - net

networks:
  net:
    driver: bridge
